package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Boja generated by hbm2java
 */
@Entity
@Table(name="boja"
    ,catalog="baza_automobila"
)
public class Boja  implements java.io.Serializable {


     private Integer bojaId;
     private String boja;
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public Boja() {
    }

	
    public Boja(String boja) {
        this.boja = boja;
    }
    public Boja(String boja, Set<Oglas> oglases) {
       this.boja = boja;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="boja_id", unique=true, nullable=false)
    public Integer getBojaId() {
        return this.bojaId;
    }
    
    public void setBojaId(Integer bojaId) {
        this.bojaId = bojaId;
    }

    
    @Column(name="boja", nullable=false, length=45)
    public String getBoja() {
        return this.boja;
    }
    
    public void setBoja(String boja) {
        this.boja = boja;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="boja")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return  boja;
    }




}


