package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BrojSedista generated by hbm2java
 */
@Entity
@Table(name="broj_sedista"
    ,catalog="baza_automobila"
)
public class BrojSedista  implements java.io.Serializable {


     private Integer brojSedistaId;
     private String brojSedista;
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public BrojSedista() {
    }

	
    public BrojSedista(String brojSedista) {
        this.brojSedista = brojSedista;
    }
    public BrojSedista(String brojSedista, Set<Oglas> oglases) {
       this.brojSedista = brojSedista;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="broj_sedista_id", unique=true, nullable=false)
    public Integer getBrojSedistaId() {
        return this.brojSedistaId;
    }
    
    public void setBrojSedistaId(Integer brojSedistaId) {
        this.brojSedistaId = brojSedistaId;
    }

    
    @Column(name="broj_sedista", nullable=false, length=45)
    public String getBrojSedista() {
        return this.brojSedista;
    }
    
    public void setBrojSedista(String brojSedista) {
        this.brojSedista = brojSedista;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="brojSedista")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return brojSedista;
    }




}


