package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmisionaKlasaMotora generated by hbm2java
 */
@Entity
@Table(name="emisiona_klasa_motora"
    ,catalog="baza_automobila"
)
public class EmisionaKlasaMotora  implements java.io.Serializable {


     private Integer emisionaKlasaMotoraId;
     private String emisionaKlasaMotora;
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public EmisionaKlasaMotora() {
    }

	
    public EmisionaKlasaMotora(String emisionaKlasaMotora) {
        this.emisionaKlasaMotora = emisionaKlasaMotora;
    }
    public EmisionaKlasaMotora(String emisionaKlasaMotora, Set<Oglas> oglases) {
       this.emisionaKlasaMotora = emisionaKlasaMotora;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="emisiona_klasa_motora_id", unique=true, nullable=false)
    public Integer getEmisionaKlasaMotoraId() {
        return this.emisionaKlasaMotoraId;
    }
    
    public void setEmisionaKlasaMotoraId(Integer emisionaKlasaMotoraId) {
        this.emisionaKlasaMotoraId = emisionaKlasaMotoraId;
    }

    
    @Column(name="emisiona_klasa_motora", nullable=false, length=45)
    public String getEmisionaKlasaMotora() {
        return this.emisionaKlasaMotora;
    }
    
    public void setEmisionaKlasaMotora(String emisionaKlasaMotora) {
        this.emisionaKlasaMotora = emisionaKlasaMotora;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="emisionaKlasaMotora")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return  emisionaKlasaMotora ;
    }




}


