package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Karoserija generated by hbm2java
 */
@Entity
@Table(name="karoserija"
    ,catalog="baza_automobila"
)
public class Karoserija  implements java.io.Serializable {


     private Integer karoserijaId;
     private String karoserija;
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public Karoserija() {
    }

	
    public Karoserija(String karoserija) {
        this.karoserija = karoserija;
    }
    public Karoserija(String karoserija, Set<Oglas> oglases) {
       this.karoserija = karoserija;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="karoserija_id", unique=true, nullable=false)
    public Integer getKaroserijaId() {
        return this.karoserijaId;
    }
    
    public void setKaroserijaId(Integer karoserijaId) {
        this.karoserijaId = karoserijaId;
    }

    
    @Column(name="karoserija", nullable=false, length=45)
    public String getKaroserija() {
        return this.karoserija;
    }
    
    public void setKaroserija(String karoserija) {
        this.karoserija = karoserija;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="karoserija")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return karoserija;
    }




}


