package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kilometraza generated by hbm2java
 */
@Entity
@Table(name="kilometraza"
    ,catalog="baza_automobila"
)
public class Kilometraza  implements java.io.Serializable {


     private Integer kilometrazaId;
     private String kilometraza;
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public Kilometraza() {
    }

	
    public Kilometraza(String kilometraza) {
        this.kilometraza = kilometraza;
    }
    public Kilometraza(String kilometraza, Set<Oglas> oglases) {
       this.kilometraza = kilometraza;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="kilometraza_id", unique=true, nullable=false)
    public Integer getKilometrazaId() {
        return this.kilometrazaId;
    }
    
    public void setKilometrazaId(Integer kilometrazaId) {
        this.kilometrazaId = kilometrazaId;
    }

    
    @Column(name="kilometraza", nullable=false, length=45)
    public String getKilometraza() {
        return this.kilometraza;
    }
    
    public void setKilometraza(String kilometraza) {
        this.kilometraza = kilometraza;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="kilometraza")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return kilometraza;
    }




}


