package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Klima generated by hbm2java
 */
@Entity
@Table(name="klima"
    ,catalog="baza_automobila"
)
public class Klima  implements java.io.Serializable {


     private Integer klimaId;
     private String klima;
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public Klima() {
    }

	
    public Klima(String klima) {
        this.klima = klima;
    }
    public Klima(String klima, Set<Oglas> oglases) {
       this.klima = klima;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="klima_id", unique=true, nullable=false)
    public Integer getKlimaId() {
        return this.klimaId;
    }
    
    public void setKlimaId(Integer klimaId) {
        this.klimaId = klimaId;
    }

    
    @Column(name="klima", nullable=false, length=45)
    public String getKlima() {
        return this.klima;
    }
    
    public void setKlima(String klima) {
        this.klima = klima;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="klima")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return klima;
    }




}


