package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Korisnik generated by hbm2java
 */
@Entity
@Table(name="korisnik"
    ,catalog="baza_automobila"
)
public class Korisnik  implements java.io.Serializable {


     private Integer korisnikId;
     private String ime;
     private String prezime;
     private String datumRodjenja;
     private String pol;
     private String zemlja;
     private String korisnickoIme;
     private String sifra;
     private String email;
     private String telefon;
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public Korisnik() {
    }

	
    public Korisnik(String ime, String prezime, String datumRodjenja, String pol, String zemlja, String korisnickoIme, String sifra, String email, String telefon) {
        this.ime = ime;
        this.prezime = prezime;
        this.datumRodjenja = datumRodjenja;
        this.pol = pol;
        this.zemlja = zemlja;
        this.korisnickoIme = korisnickoIme;
        this.sifra = sifra;
        this.email = email;
        this.telefon = telefon;
    }
    public Korisnik(String ime, String prezime, String datumRodjenja, String pol, String zemlja, String korisnickoIme, String sifra, String email, String telefon, Set<Oglas> oglases) {
       this.ime = ime;
       this.prezime = prezime;
       this.datumRodjenja = datumRodjenja;
       this.pol = pol;
       this.zemlja = zemlja;
       this.korisnickoIme = korisnickoIme;
       this.sifra = sifra;
       this.email = email;
       this.telefon = telefon;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="korisnik_id", unique=true, nullable=false)
    public Integer getKorisnikId() {
        return this.korisnikId;
    }
    
    public void setKorisnikId(Integer korisnikId) {
        this.korisnikId = korisnikId;
    }

    
    @Column(name="ime", nullable=false, length=45)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }

    
    @Column(name="prezime", nullable=false, length=45)
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    
    @Column(name="datum_rodjenja", nullable=false, length=45)
    public String getDatumRodjenja() {
        return this.datumRodjenja;
    }
    
    public void setDatumRodjenja(String datumRodjenja) {
        this.datumRodjenja = datumRodjenja;
    }

    
    @Column(name="pol", nullable=false, length=45)
    public String getPol() {
        return this.pol;
    }
    
    public void setPol(String pol) {
        this.pol = pol;
    }

    
    @Column(name="zemlja", nullable=false, length=45)
    public String getZemlja() {
        return this.zemlja;
    }
    
    public void setZemlja(String zemlja) {
        this.zemlja = zemlja;
    }

    
    @Column(name="korisnicko_ime", nullable=false, length=45)
    public String getKorisnickoIme() {
        return this.korisnickoIme;
    }
    
    public void setKorisnickoIme(String korisnickoIme) {
        this.korisnickoIme = korisnickoIme;
    }

    
    @Column(name="sifra", nullable=false, length=45)
    public String getSifra() {
        return this.sifra;
    }
    
    public void setSifra(String sifra) {
        this.sifra = sifra;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="telefon", nullable=false, length=45)
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="korisnik")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return korisnickoIme;
    }




}


