package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menjac generated by hbm2java
 */
@Entity
@Table(name="menjac"
    ,catalog="baza_automobila"
)
public class Menjac  implements java.io.Serializable {


     private Integer menjacId;
     private String menjac;
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public Menjac() {
    }

	
    public Menjac(String menjac) {
        this.menjac = menjac;
    }
    public Menjac(String menjac, Set<Oglas> oglases) {
       this.menjac = menjac;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="menjac_id", unique=true, nullable=false)
    public Integer getMenjacId() {
        return this.menjacId;
    }
    
    public void setMenjacId(Integer menjacId) {
        this.menjacId = menjacId;
    }

    
    @Column(name="menjac", nullable=false, length=45)
    public String getMenjac() {
        return this.menjac;
    }
    
    public void setMenjac(String menjac) {
        this.menjac = menjac;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="menjac")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return menjac;
    }




}


