package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Oglas generated by hbm2java
 */
@Entity
@Table(name = "oglas",
         catalog = "baza_automobila"
)
public class Oglas implements java.io.Serializable {

    private Integer oglasId;
    private Korisnik korisnik;
    private Proizvodjac proizvodjac;
    private Model model;   
    private GodinaProizvodnje godinaProizvodnje;
    private Karoserija karoserija;
    private Kubikaza kubikaza;
    private Gorivo gorivo;
    private SnagaKs snagaKs;
    private Kilometraza kilometraza;
    private EmisionaKlasaMotora emisionaKlasaMotora;
    private Pogon pogon;
    private Menjac menjac;
    private BrojVrata brojVrata;
    private BrojSedista brojSedista;
    private StranaVolana stranaVolana;
    private Klima klima;
    private Boja boja;
    private RegistrovanDo registrovanDo;
    private Ostecenje ostecenje;
    private PorekloVozila porekloVozila;
    private String telefonProdavca;
    private int cena;
    private String slika;

    public Oglas() {
    }

    public Oglas(Boja boja, BrojSedista brojSedista, BrojVrata brojVrata, EmisionaKlasaMotora emisionaKlasaMotora, GodinaProizvodnje godinaProizvodnje, Gorivo gorivo, Karoserija karoserija, Kilometraza kilometraza, Klima klima, Korisnik korisnik, Kubikaza kubikaza, Menjac menjac, Model model, Ostecenje ostecenje, Pogon pogon, PorekloVozila porekloVozila, Proizvodjac proizvodjac, RegistrovanDo registrovanDo, SnagaKs snagaKs, StranaVolana stranaVolana, String telefonProdavca, int cena) {
        this.boja = boja;
        this.brojSedista = brojSedista;
        this.brojVrata = brojVrata;
        this.emisionaKlasaMotora = emisionaKlasaMotora;
        this.godinaProizvodnje = godinaProizvodnje;
        this.gorivo = gorivo;
        this.karoserija = karoserija;
        this.kilometraza = kilometraza;
        this.klima = klima;
        this.korisnik = korisnik;
        this.kubikaza = kubikaza;
        this.menjac = menjac;
        this.model = model;
        this.ostecenje = ostecenje;
        this.pogon = pogon;
        this.porekloVozila = porekloVozila;
        this.proizvodjac = proizvodjac;
        this.registrovanDo = registrovanDo;
        this.snagaKs = snagaKs;
        this.stranaVolana = stranaVolana;
        this.telefonProdavca = telefonProdavca;
        this.cena = cena;
    }

    public Oglas(Korisnik korisnik, Proizvodjac proizvodjac, Model model, GodinaProizvodnje godinaProizvodnje, Karoserija karoserija, Kubikaza kubikaza, Gorivo gorivo, SnagaKs snagaKs, Kilometraza kilometraza, EmisionaKlasaMotora emisionaKlasaMotora, Pogon pogon, Menjac menjac, BrojVrata brojVrata, BrojSedista brojSedista, StranaVolana stranaVolana, Klima klima, Boja boja, RegistrovanDo registrovanDo, Ostecenje ostecenje, PorekloVozila porekloVozila, String telefonProdavca, int cena, String slika) {
        this.korisnik = korisnik;
        this.proizvodjac = proizvodjac;
        this.model = model;
        this.godinaProizvodnje = godinaProizvodnje;
        this.karoserija = karoserija;
        this.kubikaza = kubikaza;
        this.gorivo = gorivo;
        this.snagaKs = snagaKs;
        this.kilometraza = kilometraza;
        this.emisionaKlasaMotora = emisionaKlasaMotora;
        this.pogon = pogon;
        this.menjac = menjac;
        this.brojVrata = brojVrata;
        this.brojSedista = brojSedista;
        this.stranaVolana = stranaVolana;
        this.klima = klima;
        this.boja = boja;
        this.registrovanDo = registrovanDo;
        this.ostecenje = ostecenje;
        this.porekloVozila = porekloVozila;
        this.telefonProdavca = telefonProdavca;
        this.cena = cena;
        this.slika = slika;
    }

    

   

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "oglas_id", unique = true, nullable = false)
    public Integer getOglasId() {
        return this.oglasId;
    }

    public void setOglasId(Integer oglasId) {
        this.oglasId = oglasId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "boja_id", nullable = false)
    public Boja getBoja() {
        return this.boja;
    }

    public void setBoja(Boja boja) {
        this.boja = boja;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "broj_sedista_id", nullable = false)
    public BrojSedista getBrojSedista() {
        return this.brojSedista;
    }

    public void setBrojSedista(BrojSedista brojSedista) {
        this.brojSedista = brojSedista;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "broj_vrata_id", nullable = false)
    public BrojVrata getBrojVrata() {
        return this.brojVrata;
    }

    public void setBrojVrata(BrojVrata brojVrata) {
        this.brojVrata = brojVrata;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emisiona_klasa_motora_id", nullable = false)
    public EmisionaKlasaMotora getEmisionaKlasaMotora() {
        return this.emisionaKlasaMotora;
    }

    public void setEmisionaKlasaMotora(EmisionaKlasaMotora emisionaKlasaMotora) {
        this.emisionaKlasaMotora = emisionaKlasaMotora;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "godina_proizvodnje_id", nullable = false)
    public GodinaProizvodnje getGodinaProizvodnje() {
        return this.godinaProizvodnje;
    }

    public void setGodinaProizvodnje(GodinaProizvodnje godinaProizvodnje) {
        this.godinaProizvodnje = godinaProizvodnje;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gorivo_id", nullable = false)
    public Gorivo getGorivo() {
        return this.gorivo;
    }

    public void setGorivo(Gorivo gorivo) {
        this.gorivo = gorivo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "karoserija_id", nullable = false)
    public Karoserija getKaroserija() {
        return this.karoserija;
    }

    public void setKaroserija(Karoserija karoserija) {
        this.karoserija = karoserija;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "kilometraza_id", nullable = false)
    public Kilometraza getKilometraza() {
        return this.kilometraza;
    }

    public void setKilometraza(Kilometraza kilometraza) {
        this.kilometraza = kilometraza;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "klima_id", nullable = false)
    public Klima getKlima() {
        return this.klima;
    }

    public void setKlima(Klima klima) {
        this.klima = klima;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "korisnik_id", nullable = false)
    public Korisnik getKorisnik() {
        return this.korisnik;
    }

    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "kubikaza_id", nullable = false)
    public Kubikaza getKubikaza() {
        return this.kubikaza;
    }

    public void setKubikaza(Kubikaza kubikaza) {
        this.kubikaza = kubikaza;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "menjac_id", nullable = false)
    public Menjac getMenjac() {
        return this.menjac;
    }

    public void setMenjac(Menjac menjac) {
        this.menjac = menjac;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "model_id", nullable = false)
    public Model getModel() {
        return this.model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ostecenje_id", nullable = false)
    public Ostecenje getOstecenje() {
        return this.ostecenje;
    }

    public void setOstecenje(Ostecenje ostecenje) {
        this.ostecenje = ostecenje;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pogon_id", nullable = false)
    public Pogon getPogon() {
        return this.pogon;
    }

    public void setPogon(Pogon pogon) {
        this.pogon = pogon;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "poreklo_vozila_id", nullable = false)
    public PorekloVozila getPorekloVozila() {
        return this.porekloVozila;
    }

    public void setPorekloVozila(PorekloVozila porekloVozila) {
        this.porekloVozila = porekloVozila;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "proizvodjac_id", nullable = false)
    public Proizvodjac getProizvodjac() {
        return this.proizvodjac;
    }

    public void setProizvodjac(Proizvodjac proizvodjac) {
        this.proizvodjac = proizvodjac;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "registrovan_do_id", nullable = false)
    public RegistrovanDo getRegistrovanDo() {
        return this.registrovanDo;
    }

    public void setRegistrovanDo(RegistrovanDo registrovanDo) {
        this.registrovanDo = registrovanDo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "snaga_ks_id", nullable = false)
    public SnagaKs getSnagaKs() {
        return this.snagaKs;
    }

    public void setSnagaKs(SnagaKs snagaKs) {
        this.snagaKs = snagaKs;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "strana_volana_id", nullable = false)
    public StranaVolana getStranaVolana() {
        return this.stranaVolana;
    }

    public void setStranaVolana(StranaVolana stranaVolana) {
        this.stranaVolana = stranaVolana;
    }

    @Column(name = "telefon_prodavca", nullable = false, length = 45)
    public String getTelefonProdavca() {
        return this.telefonProdavca;
    }

    public void setTelefonProdavca(String telefonProdavca) {
        this.telefonProdavca = telefonProdavca;
    }

    @Column(name = "cena", nullable = false)
    public int getCena() {
        return this.cena;
    }

    public void setCena(int cena) {
        this.cena = cena;
    }

    @Column(name = "slika", length = 100)
    public String getSlika() {
        return this.slika;
    }

    public void setSlika(String slika) {
        this.slika = slika;
    }

}
