package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ostecenje generated by hbm2java
 */
@Entity
@Table(name="ostecenje"
    ,catalog="baza_automobila"
)
public class Ostecenje  implements java.io.Serializable {


     private Integer ostecenjeId;
     private String ostecenje;
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public Ostecenje() {
    }

	
    public Ostecenje(String ostecenje) {
        this.ostecenje = ostecenje;
    }
    public Ostecenje(String ostecenje, Set<Oglas> oglases) {
       this.ostecenje = ostecenje;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ostecenje_id", unique=true, nullable=false)
    public Integer getOstecenjeId() {
        return this.ostecenjeId;
    }
    
    public void setOstecenjeId(Integer ostecenjeId) {
        this.ostecenjeId = ostecenjeId;
    }

    
    @Column(name="ostecenje", nullable=false, length=45)
    public String getOstecenje() {
        return this.ostecenje;
    }
    
    public void setOstecenje(String ostecenje) {
        this.ostecenje = ostecenje;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ostecenje")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return ostecenje;
    }




}


