package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pogon generated by hbm2java
 */
@Entity
@Table(name="pogon"
    ,catalog="baza_automobila"
)
public class Pogon  implements java.io.Serializable {


     private Integer pogonId;
     private String pogon;
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public Pogon() {
    }

	
    public Pogon(String pogon) {
        this.pogon = pogon;
    }
    public Pogon(String pogon, Set<Oglas> oglases) {
       this.pogon = pogon;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pogon_id", unique=true, nullable=false)
    public Integer getPogonId() {
        return this.pogonId;
    }
    
    public void setPogonId(Integer pogonId) {
        this.pogonId = pogonId;
    }

    
    @Column(name="pogon", nullable=false, length=45)
    public String getPogon() {
        return this.pogon;
    }
    
    public void setPogon(String pogon) {
        this.pogon = pogon;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pogon")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return  pogon;
    }




}


