package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PorekloVozila generated by hbm2java
 */
@Entity
@Table(name="poreklo_vozila"
    ,catalog="baza_automobila"
)
public class PorekloVozila  implements java.io.Serializable {


     private Integer porekloVozilaId;
     private String porekloVozila;
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public PorekloVozila() {
    }

	
    public PorekloVozila(String porekloVozila) {
        this.porekloVozila = porekloVozila;
    }
    public PorekloVozila(String porekloVozila, Set<Oglas> oglases) {
       this.porekloVozila = porekloVozila;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="poreklo_vozila_id", unique=true, nullable=false)
    public Integer getPorekloVozilaId() {
        return this.porekloVozilaId;
    }
    
    public void setPorekloVozilaId(Integer porekloVozilaId) {
        this.porekloVozilaId = porekloVozilaId;
    }

    
    @Column(name="poreklo_vozila", nullable=false, length=45)
    public String getPorekloVozila() {
        return this.porekloVozila;
    }
    
    public void setPorekloVozila(String porekloVozila) {
        this.porekloVozila = porekloVozila;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="porekloVozila")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return porekloVozila;
    }




}


