package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proizvodjac generated by hbm2java
 */
@Entity
@Table(name="proizvodjac"
    ,catalog="baza_automobila"
)
public class Proizvodjac  implements java.io.Serializable {


     private Integer proizvodjacId;
     private String proizvodjacIme;
     private Set<Model> models = new HashSet<Model>(0);
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public Proizvodjac() {
    }

	
    public Proizvodjac(String proizvodjacIme) {
        this.proizvodjacIme = proizvodjacIme;
    }
    public Proizvodjac(String proizvodjacIme, Set<Model> models, Set<Oglas> oglases) {
       this.proizvodjacIme = proizvodjacIme;
       this.models = models;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="proizvodjac_id", unique=true, nullable=false)
    public Integer getProizvodjacId() {
        return this.proizvodjacId;
    }
    
    public void setProizvodjacId(Integer proizvodjacId) {
        this.proizvodjacId = proizvodjacId;
    }

    
    @Column(name="proizvodjac_ime", nullable=false, length=45)
    public String getProizvodjacIme() {
        return this.proizvodjacIme;
    }
    
    public void setProizvodjacIme(String proizvodjacIme) {
        this.proizvodjacIme = proizvodjacIme;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proizvodjac")
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proizvodjac")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return proizvodjacIme;
    }




}


