package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RegistrovanDo generated by hbm2java
 */
@Entity
@Table(name="registrovan_do"
    ,catalog="baza_automobila"
)
public class RegistrovanDo  implements java.io.Serializable {


     private Integer registrovanDoId;
     private String registrovanDo;
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public RegistrovanDo() {
    }

	
    public RegistrovanDo(String registrovanDo) {
        this.registrovanDo = registrovanDo;
    }
    public RegistrovanDo(String registrovanDo, Set<Oglas> oglases) {
       this.registrovanDo = registrovanDo;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="registrovan_do_id", unique=true, nullable=false)
    public Integer getRegistrovanDoId() {
        return this.registrovanDoId;
    }
    
    public void setRegistrovanDoId(Integer registrovanDoId) {
        this.registrovanDoId = registrovanDoId;
    }

    
    @Column(name="registrovan_do", nullable=false, length=45)
    public String getRegistrovanDo() {
        return this.registrovanDo;
    }
    
    public void setRegistrovanDo(String registrovanDo) {
        this.registrovanDo = registrovanDo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="registrovanDo")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return registrovanDo;
    }




}


