package Entity;
// Generated Jul 3, 2017 12:11:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StranaVolana generated by hbm2java
 */
@Entity
@Table(name="strana_volana"
    ,catalog="baza_automobila"
)
public class StranaVolana  implements java.io.Serializable {


     private Integer stranaVolanaId;
     private String stranaVolana;
     private Set<Oglas> oglases = new HashSet<Oglas>(0);

    public StranaVolana() {
    }

	
    public StranaVolana(String stranaVolana) {
        this.stranaVolana = stranaVolana;
    }
    public StranaVolana(String stranaVolana, Set<Oglas> oglases) {
       this.stranaVolana = stranaVolana;
       this.oglases = oglases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="strana_volana_id", unique=true, nullable=false)
    public Integer getStranaVolanaId() {
        return this.stranaVolanaId;
    }
    
    public void setStranaVolanaId(Integer stranaVolanaId) {
        this.stranaVolanaId = stranaVolanaId;
    }

    
    @Column(name="strana_volana", nullable=false, length=45)
    public String getStranaVolana() {
        return this.stranaVolana;
    }
    
    public void setStranaVolana(String stranaVolana) {
        this.stranaVolana = stranaVolana;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stranaVolana")
    public Set<Oglas> getOglases() {
        return this.oglases;
    }
    
    public void setOglases(Set<Oglas> oglases) {
        this.oglases = oglases;
    }

    @Override
    public String toString() {
        return stranaVolana;
    }




}


